db:
  datasource: root:asdf@tcp(localhost:3306)/search_nova?charset=utf8&parseTime=true&loc=Local
logger:
  dir: /tmp/search-nova/log
  level: debug
manager:
  server:
    port: 8090
server:
  cors:
    access-control-allow-origin: http://localhost:8081
  mode: release
  port: 8080
assets:
  root: ./assets
elasticsearch:
  password: TCzhcDyUPVuwVPAcYJw=
