db:
    datasource: root:asdf@tcp(localhost:3306)/search_nova?charset=utf8&parseTime=true
logger:
    dir: /tmp/search-nova/log
    level: debug
manager:
    server:
        port: 8090
server:
    cors:
        access-control-allow-origin: http://localhost:8081
    mode: debug
    port: 8080
assets:
    root: ./assets
    js: ./assets/js
    css: ./assets/css
    img: ./assets/img
